from app.feedback.retrieveText.convertDocxTxtToText import getTXTText, getDOCXText
from app.feedback.retrieveText.convertPdfToText import getPDFText
from app.feedback.content import sourceIntegration
from app.feedback.languageAndStyle import feedbackLanguageStyle
from app.feedback.getMistakesInformation import getMistakesInformationStructure, getMistakesInformationStyle
from app.feedback.structureCheck import getStructureScore
from app.fileapi.convert import convertDocx, convertTxt
from app.scoreapi.scores import setScoreDB, setExplanationDB
from app import cache
import nltk
from nltk.corpus import stopwords

def genFeedback(file):
    '''
        Generate the feedback for a specific file, that is run the methods to generate the explanations and scores for 
        the file, for each of the four categories. To do this, we first retrieve the text by means of the get...Text methods. 
        Lastly, we run the getMistakeInformation... methods and add these explanations of the mistakes to the database.
        attributes:
            fileId: The file Id of the file we are currently generating feedback for.
            fileType: The FileType of the file we are currently generating feedback for.
            path: The path of the file we are currently generating feedback for.
            userId: The User id of the user we are currently generating feedback for.
            references: References as retrieved from the get...Text method.
            englishStopwords: The english stopwords from the nltk library, as retrieved by the getEnglishStopwords method.
            scoreContent: The score of the content as generated by the sourceIntegration method.
            explanationContent: The explanations of the integration and content, as retrieved from the sourceIntegration method.
            mistakesStyle: The mistakes from the language and style, as retrieved from the feedbackLanguageStyle method.
            scoreStyle: The score for the language and style, as retrieved from the feedbackLanguageStyle method.
            scoreStructure: The score for the structure, as retrieved from the getStructureScore method. 
            explanationsStructure: The explanations for the structure, as retrieved from the getStructureScore method.
        arguments: 
            file: The file we are generating the feedback for and uploading this feedback for to the database. 
        returns: 
            True if the feedback has been successfully generated and added to the database, false with an error message otherwise.
    '''
    # Retrieve the required information from the file:
    fileId = file.id
    fileType = file.fileType
    path = file.path
    userId = file.userId
    try:
        # Initialize empty string for the references:
        references = ''
        # Retrieve the text from each fileType, and convert this file if required:
        if fileType == '.docx':
            text, references = getDOCXText(path)
            path = convertDocx(path)
            textStructure = text
        elif fileType == '.pdf':
            textStructure = getPDFText(path, returnReferencesText=True)
            text, references = getPDFText(path, returnReferences=True)
        elif fileType == '.txt':
            text = getTXTText(path)
            path = convertTxt(path)
            textStructure = text
        englishStopwords = getEnglishStopwords()
        # Generate the score for the sourceIntegration, language and style and structure:
        mistakesStyle, scoreStyle = feedbackLanguageStyle(text)
        scoreStructure, explanationsStructure = getStructureScore(textStructure)
        scoreContent, explanationContent = sourceIntegration(text, references, englishStopwords, userId)
        # Set the score correctly in the database:
        setScoreDB(fileId, scoreStyle, -2, scoreStructure, scoreContent)
        # Set the feedback for all categories by either using a separate method or by simply using setExplanationDB:
        setFeedbackStyle(mistakesStyle, path, fileId)
        setFeedbackStructure(explanationsStructure, path, fileId)
        setExplanationDB(fileId = fileId, explId = -1, type = 3, explanation = explanationContent)
    except Exception as e:
        return False, str(e)
    return True, 'Feedback has been generated!'

def setFeedbackStyle(mistakesStyle, path, fileId):
    '''
        Run the getMistakesInformationStructure method to get the location of the mistakes in the language & style 
        category and upload these explanations to the database.
        attributes:
            feedbacks: List with feedback as retrieved by the getMistakesInformationStyle method.
            X1: The first x coordinate as retrieved from the getMistakesInformationStyle method.
            X2: The second x coordinate as retrieved from the getMistakesInformationStyle method.
            Y1: The first y coordinate as retrieved from the getMistakesInformationStyle method.
            Y1: The second y coordinate as retrieved from the getMistakesInformationStyle method.
            type: The type of the explanation as retrieved from the getMistakesInformationStyle method.
            expl: The explanation text as retrieved from the getMistakesInformationStyle method.
            mistake: The mistake text as retrieved from the getMistakesInformationStyle method.
            replacements: Possible replacements as retrieved from the getMistakesInformationStyle method.
        arguments: 
            mistakesStyle: mistakes as gotten from the feedbackLanguageStyle method.
            path: path corresponding to the pdf file, the coordinates of the mistakes should be retrieved from.
            fileId: fileId of the file we retrieve the mistakes from and put the mistakes from in the database.
    '''
    # Retrieve the mistakes with locations and possible replacements from the getMistakesInformationStyle method:
    feedbacks = getMistakesInformationStyle(mistakesStyle, path)
    # For each mistake, add it to the database together with required information:
    for (X1, Y1, X2, Y2, type, expl, mistake, replacements) in feedbacks:
        # Initialize the replacements to the empty string:
        replacement1 = replacement2 = replacement3 = ''
        # Add as much replacements as required, at most 3 and at least 0:
        if len(replacements) > 0:
           replacement1 = replacements[0]
        if len(replacements) > 1:
            replacement2 = replacements[1]
        if len(replacements) > 2:
            replacement3 = replacements[2]
        # Upload the actual explanations tot he database:
        setExplanationDB(X1 = X1, Y1 = Y1, X2 = X2, Y2 = Y2, fileId = fileId, explId = -1, type = type, explanation = expl, 
        mistakeText = mistake, replacement1 = replacement1, replacement2 = replacement2, replacement3 = replacement3)

def setFeedbackStructure(mistakesStructure, path, fileId):
    '''
        Run the getMistakesInformationStructure method to get the location of the mistakes in the structure category 
        and add each mistake to the database using the setExplanationDB method. 
        attributes:
            mistakes: Mistakes as retrieved by the getMistakesInformationStructure method.
            X1: The first x coordinate as retrieved from the getMistakesInformationStructure method.
            X2: The second x coordinate as retrieved from the getMistakesInformationStructure method.
            Y1: The first y coordinate as retrieved from the getMistakesInformationStructure method.
            Y1: The second y coordinate as retrieved from the getMistakesInformationStructure method.
            type: The type of the explanation as retrieved from the getMistakesInformationStructure method.
            expl: The explanation text as retrieved from the getMistakesInformationStructure method.
            mistake: The mistake text as retrieved from the getMistakesInformationStructure method.
        arguments: 
            mistakesStructure: mistakes as gotten from the getStructureScore method.
            path: path corresponding to the pdf file, the coordinates of the mistakes should be retrieved from.
            fileId: fileId of the file we retrieve the mistakes from and put the mistakes from in the database.
    '''
    # Retrieve the mistakes with locations from the getMistakesInformationStructure method:
    mistakes = getMistakesInformationStructure(mistakesStructure, path)
    # For each mistake, add it to the database together with all required data:
    for (X1, Y1, X2, Y2, type, expl, mistake) in mistakes:
        setExplanationDB(X1 = X1, Y1 = Y1, X2 = X2, Y2 = Y2, fileId = fileId, explId = -1, 
            type = type, explanation = expl, mistakeText = mistake)


@cache.memoize(30*24*60*60)
def getEnglishStopwords():
    ''' 
        Method to retrieve english stop words from the nltk library. Downloads the punkt and stopwords, to be able to use the 
        word_tokenize method. This englishStopwords list as downloaded from nltk is memoized, that is stored, 
        for a month using flask_cache.
        returns:
            englishStopwords: The english stopwords from the nltk library.
    '''
    nltk.download('stopwords')
    nltk.download('punkt')
    englishStopwords = stopwords.words('english')
    return englishStopwords