FROM goacme/lego
ENV NAMECOM_USERNAME itzjustrick1@gmx.com
ENV NAMECOM_API_TOKEN cae4f4fa70e761e1988fae6f91ff9581ca6a2578
CMD lego --email itzjustrick1@gmx.com --dns namedotcom --domains writingdashboard.xyz run