"""empty message

Revision ID: fa0879cf3b3b
Revises: 
Create Date: 2022-07-03 21:08:06.285578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa0879cf3b3b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('role', sa.String(length=32), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=120), nullable=True),
    sa.Column('passwordHash', sa.String(length=128), nullable=True),
    sa.Column('trackable', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('clicks',
    sa.Column('clickId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('url', sa.String(length=64), nullable=True),
    sa.Column('eventType', sa.String(length=32), nullable=True),
    sa.Column('actionId', sa.String(length=384), nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], ),
    sa.PrimaryKeyConstraint('clickId')
    )
    op.create_index(op.f('ix_clicks_userId'), 'clicks', ['userId'], unique=False)
    op.create_table('files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.Column('path', sa.String(), nullable=True),
    sa.Column('filename', sa.String(length=256), nullable=True),
    sa.Column('fileType', sa.String(length=5), nullable=True),
    sa.Column('courseCode', sa.String(length=16), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_files_filename'), 'files', ['filename'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.Column('projectName', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_projectName'), 'projects', ['projectName'], unique=False)
    op.create_table('explanations',
    sa.Column('fileId', sa.Integer(), nullable=True),
    sa.Column('explId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type', sa.Integer(), nullable=True),
    sa.Column('explanation', sa.String(), nullable=True),
    sa.Column('mistakeText', sa.String(), nullable=True),
    sa.Column('X1', sa.Float(), nullable=True),
    sa.Column('X2', sa.Float(), nullable=True),
    sa.Column('Y1', sa.Float(), nullable=True),
    sa.Column('Y2', sa.Float(), nullable=True),
    sa.Column('replacement1', sa.String(), nullable=True),
    sa.Column('replacement2', sa.String(), nullable=True),
    sa.Column('replacement3', sa.String(), nullable=True),
    sa.Column('feedbackVersion', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['fileId'], ['files.id'], ),
    sa.PrimaryKeyConstraint('explId')
    )
    op.create_index('idx_fileId_Type', 'explanations', ['fileId', 'type'], unique=False)
    op.create_index('idx_fileId_coordinates', 'explanations', ['fileId', 'X1', 'X2', 'Y1', 'Y2'], unique=False)
    op.create_index(op.f('ix_explanations_fileId'), 'explanations', ['fileId'], unique=False)
    op.create_table('participanttoproject',
    sa.Column('userId', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('projectId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['projectId'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], ),
    sa.PrimaryKeyConstraint('userId')
    )
    op.create_table('scores',
    sa.Column('fileId', sa.Integer(), nullable=False),
    sa.Column('scoreStyle', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('scoreCohesion', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('scoreStructure', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('scoreIntegration', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('feedbackVersion', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['fileId'], ['files.id'], ),
    sa.PrimaryKeyConstraint('fileId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scores')
    op.drop_table('participanttoproject')
    op.drop_index(op.f('ix_explanations_fileId'), table_name='explanations')
    op.drop_index('idx_fileId_coordinates', table_name='explanations')
    op.drop_index('idx_fileId_Type', table_name='explanations')
    op.drop_table('explanations')
    op.drop_index(op.f('ix_projects_projectName'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_files_filename'), table_name='files')
    op.drop_table('files')
    op.drop_index(op.f('ix_clicks_userId'), table_name='clicks')
    op.drop_table('clicks')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
