"""user and participant

Revision ID: 16ff4b67d603
Revises: 
Create Date: 2022-05-19 10:06:48.060872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16ff4b67d603'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('participant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_participant_username'), 'participant', ['username'], unique=True)
    op.add_column('user', sa.Column('password_hash', sa.String(length=128), nullable=True))
    op.drop_index('ix_user_email', table_name='user')
    op.drop_column('user', 'email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.create_index('ix_user_email', 'user', ['email'], unique=False)
    op.drop_column('user', 'password_hash')
    op.drop_index(op.f('ix_participant_username'), table_name='participant')
    op.drop_table('participant')
    # ### end Alembic commands ###
