"""new table

Revision ID: 1cfe73a890f6
Revises: 
Create Date: 2022-06-15 13:35:16.232693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1cfe73a890f6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('role', sa.String(length=32), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=120), nullable=True),
    sa.Column('passwordHash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.Column('path', sa.String(), nullable=True),
    sa.Column('filename', sa.String(length=256), nullable=True),
    sa.Column('fileType', sa.String(length=5), nullable=True),
    sa.Column('courseCode', sa.String(length=16), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_files_filename'), 'files', ['filename'], unique=False)
    op.create_table('explanations',
    sa.Column('fileId', sa.Integer(), nullable=False),
    sa.Column('explId', sa.Integer(), nullable=False),
    sa.Column('type', sa.Integer(), nullable=True),
    sa.Column('explanation', sa.String(), nullable=True),
    sa.Column('mistakeText', sa.String(), nullable=True),
    sa.Column('X1', sa.Float(), nullable=True),
    sa.Column('X2', sa.Float(), nullable=True),
    sa.Column('Y1', sa.Float(), nullable=True),
    sa.Column('Y2', sa.Float(), nullable=True),
    sa.Column('replacement1', sa.String(), nullable=True),
    sa.Column('replacement2', sa.String(), nullable=True),
    sa.Column('replacement3', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['fileId'], ['files.id'], ),
    sa.PrimaryKeyConstraint('fileId', 'explId')
    )
    op.create_table('scores',
    sa.Column('fileId', sa.Integer(), nullable=False),
    sa.Column('scoreStyle', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('scoreCohesion', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('scoreStructure', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('scoreIntegration', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['fileId'], ['files.id'], ),
    sa.PrimaryKeyConstraint('fileId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scores')
    op.drop_table('explanations')
    op.drop_index(op.f('ix_files_filename'), table_name='files')
    op.drop_table('files')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
