"""single

Revision ID: 7f3c39191304
Revises: 9b5663e76725
Create Date: 2022-05-19 11:48:45.120735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f3c39191304'
down_revision = '9b5663e76725'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('participant')
    op.drop_table('student')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id'], ['user.id'], name='student_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='student_pkey')
    )
    op.create_table('participant',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id'], ['user.id'], name='participant_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='participant_pkey')
    )
    # ### end Alembic commands ###
