"""Inheritance

Revision ID: 8bc6e46bb2c6
Revises: 16ff4b67d603
Create Date: 2022-05-19 10:47:49.798182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bc6e46bb2c6'
down_revision = '16ff4b67d603'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_participant_username', table_name='participant')
    op.drop_table('participant')
    op.add_column('user', sa.Column('type', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'type')
    op.create_table('participant',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('password_hash', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='participant_pkey')
    )
    op.create_index('ix_participant_username', 'participant', ['username'], unique=False)
    # ### end Alembic commands ###
